#!/bin/bash

echo "🔧 Fixing DEV Firebase Configuration"
echo "====================================="
echo ""
echo "The error means the google-services.json doesn't match the package name."
echo ""
echo "📋 Steps to Fix:"
echo ""
echo "1. Go to Firebase Console:"
echo "   https://console.firebase.google.com/project/job-tracker-dev-79ca2"
echo ""
echo "2. Click on Project Settings (⚙️ icon)"
echo ""
echo "3. Scroll to 'Your apps' section"
echo ""
echo "4. You'll see the Android app. Click on it"
echo ""
echo "5. If the package name is 'com.example.job_tracker' (without .dev):"
echo "   - Click 'Add another package name'"
echo "   - Enter: com.example.job_tracker.dev"
echo "   - Save"
echo ""
echo "6. OR if you need to register a new app:"
echo "   - Go back to project overview"
echo "   - Click 'Add app' → Android"
echo "   - Package name: com.example.job_tracker.dev"
echo "   - App nickname: Job Tracker DEV Android"
echo "   - Click 'Register app'"
echo ""
echo "7. Download the NEW google-services.json"
echo ""
echo "8. Replace the file at:"
echo "   android/app/src/dev/google-services.json"
echo ""
echo "9. Verify the file contains:"
echo "   \"package_name\": \"com.example.job_tracker.dev\""
echo ""
echo "10. Try building again:"
echo "    flutter build apk --flavor dev -t lib/main_dev.dart"
echo ""
echo "====================================="
