#!/bin/bash

# Firebase DEV Setup Helper
# This script helps you complete the DEV environment setup

echo "🔥 Firebase DEV Environment Setup"
echo "=================================="
echo ""
echo "Your DEV Firebase project: job-tracker-dev-79ca2"
echo "✅ Firebase options file generated: lib/firebase_options_dev.dart"
echo ""
echo "📋 Next Steps:"
echo ""
echo "1️⃣  Download google-services.json for ANDROID:"
echo "   - Go to: https://console.firebase.google.com/project/job-tracker-dev-79ca2"
echo "   - Click the Android app"
echo "   - Download google-services.json"
echo "   - Place it in: android/app/src/dev/google-services.json"
echo ""
echo "2️⃣  Download GoogleService-Info.plist for iOS:"
echo "   - Go to: https://console.firebase.google.com/project/job-tracker-dev-79ca2"
echo "   - Click the iOS app"
echo "   - Download GoogleService-Info.plist"
echo "   - Rename to: GoogleService-Info-dev.plist"
echo "   - Place it in: ios/Runner/GoogleService-Info-dev.plist"
echo ""
echo "3️⃣  Enable Firebase Services:"
echo "   - Authentication → Google Sign-In"
echo "   - Firestore Database → Create (test mode)"
echo "   - Storage → Create bucket"
echo ""
echo "4️⃣  Test the DEV app:"
echo "   ./run_dev.sh"
echo ""
echo "=================================="
echo "Need help? Check FLAVORS_QUICK_START.md"
